
import img1 from "../img/1.jpg";
import img2 from "../img/2.jpg";
import img3 from "../img/3.jpg";
import img4 from "../img/4.jpg";
import img5 from "../img/5.jpg";
import img6 from "../img/6.jpg";
import img7 from "../img/7.jpg";
import img8 from "../img/8.jpg";
import img9 from "../img/9.jpg";
import img10 from "../img/10.jpg";
import img11 from "../img/11.jpg";
import img12 from "../img/12.jpg";

export const brands = [

'Anteater',
'Anti-hero',

'Baker',
'Billabong',
'Chocolate',

'Dragon',

'Eastcoast',
'Electric',
'Lucky',
'Miller Division',
'Oneskee',
'Prime',
];

export const PRODUCTS = [
    {
      "id": 1,
      "title": "Skateboard Anteater 95mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 1700,
      "category": "Anteater",
      "image": img1,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 2,
      "title": "Skateboard Anteater 70mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 1800,
      "category": "Anteater",
      "image": img2,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 3,
      "title": "Skateboard Anti-hero 70mm",
      "size": "105cm",
      "material": "oak",
      "country": "Ukraine",
      "price": 2300,
      "category": "Anti-hero",
      "image": img3,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 4,
      "title": "Skateboard Chocolate 70mm",
      "size": "105cm",
      "material": "oak",
      "country": "Ukraine",
      "price": 959,
      "category": "Chocolate",
      "image": img6,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,

    },
    {
      "id": 5,
      "title": "Skateboard Billabong 75mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 695,
      "category": "Billabong",
      "image": img5,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 6,
      "title": "Skateboard Dragon 99mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 3069,
      "category": "Dragon",
      "image": img8,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,

    },
    {
      "id": 7,
      "title": "Skateboard Eastcoast 99mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 1009.99,
      "category": "Eastcoast",
      "image": img9,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 8,
      "title": "Skateboard Anti-hero 99mm",
      "size": "105cm",
      "material": "oak",
      "country": "Ukraine",
      "price": 999.99,
      "category": "Anti-hero",
      "image": img4,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 10,
      "title": "Skateboard Electric 75mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 1090,
      "category": "Electric",
      "image": img12,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 11,
      "title": "Skateboard Chocolate 96mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 1400,
      "category": "Chocolate",
      "image": img7,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 12,
      "title": "Skateboard Lucky 72mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 6000,
      "category": "Lucky",
      "image": img1,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 13,
      "title": "Skateboard Lucky 98mm",
      "size": "105cm",
      "material": "oak",
      "country": "Ukraine",
      "price": 2599,
      "category": "Lucky",
      "image": img2,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 14,
      "title": "Skateboard Miller Division 80mm",
      "size": "105cm",
      "material": "oak",
      "country": "Ukraine",
      "price": 999.99,
      "category": "Miller Division",
      "image": img3,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 15,
      "title": "Skateboard Eastcoast 99mm",
      "size": "105cm",
      "material": "oak",
      "country": "Ukraine",
      "price": 756.99,
      "category": "Eastcoast",
      "image": img10,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 16,
      "title": "Skateboard Miller Division 74mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 2229.95,
      "category": "Miller Division",
      "image": img6,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 17,
      "title": "Skateboard Lucky 80mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 3900.99,
      "category": "Lucky",
      "image": img7,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 18,
      "title": "Skateboard Oneskee 80mm",
      "size": "105cm",
      "material": "oak",
      "country": "Ukraine",
      "price": 900.85,
      "category": "Oneskee",
      "image": img12,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 19,
      "title": "Skateboard Eastcoast 80mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 7200,
      "category": "Eastcoast",
      "image": img11,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 20,
      "title": "Skateboard Oneskee 95mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 1299,
      "category": "Oneskee",
      "image": img9,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 21,
      "title": "Skateboard Lucky 98mm",
      "size": "105cm",
      "material": "oak",
      "country": "Ukraine",
      "price": 3999,
      "category": "Lucky",
      "image": img7,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 22,
      "title": "Skateboard Prime 80mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 999.85,
      "category": "Prime",
      "image": img5,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 23,
      "title": "Skateboard Eastcoast 102mm",
      "size": "105cm",
      "material": "oak",
      "country": "Ukraine",
      "price": 700.95,
      "category": "Eastcoast",
      "image": img3,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 24,
      "title": "Skateboard Prime 80mm",
      "size": "105cm",
      "material": "Maple",
      "country": "Ukraine",
      "price": 1200.99,
      "category": "Prime",
      "image": img4,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
    {
      "id": 25,
      "title": "Skateboard Lucky 72mm",
      "size": "105cm",
      "material": "oak",
      "country": "Ukraine",
      "price": 5400,
      "category": "Lucky",
      "image": img1,
      "seller": 'Rozetka',
      "wheels": 95,
      "limit": 60,
    },
  ]